window.WORK_ITEMS = [
  { id:'facts', featured:true, kind:'Field Note 001', title:'What If Your Facts Are Wrong?', dek:'Certainty isn’t evidence of truth. Usually it’s just a measure of how long a fact has gone unquestioned.', image:'assets/images/daily-observer.png', href:'assets/perspectives/what-if-your-facts-are-wrong.pdf', action:'Read the field note' },
  { id:'rlt', featured:true, kind:'White Paper', title:'The Second Wave Should Go Narrow', dek:'The next generation of RLT should prove more, in fewer patients, against a harder standard.', image:'assets/images/next-decade-rlt.png', href:'assets/perspectives/second-wave-should-go-narrow.pdf', action:'Open the white paper' },
  { id:'coordination', featured:true, kind:'White Paper', title:'The Coordination Problem', dek:'Complexity is often only a polite word for unresolved structure. That’s where performance dies.', image:'assets/images/leadership-complexity.png', href:'assets/perspectives/the-coordination-problem.pdf', action:'Read the paper' },
  { id:'narrative-infrastructure', featured:true, kind:'Field Note', title:'Narrative Infrastructure', dek:'A strategy for how biotech could build trust before diagnosis—and become the lens through which people understand their own bodies.', image:'assets/images/narrative-infrastructure-cover.png', href:'assets/perspectives/narrative-infrastructure.pdf', action:'Read the field note' },
  { id:'myhouse', featured:false, kind:'Original Concept', title:'My House', dek:'A global ranking system for football talent—built before the infrastructure exists. The upload is the competition. Rank is the product.', visual:'board', restricted:true, action:'View the concept' },
  { id:'decay', featured:false, kind:'Organizational Diagnosis', title:'Positional Decay', dek:'How organizations hollow themselves out before a competitor ever beats them.', image:'assets/images/next-decade-rlt.png', href:'assets/perspectives/positional-decay.pdf', action:'Open the file' },
  { id:'terrain', featured:false, kind:'Brand Strategy', title:'The Market Is Terrain, Not Author', dek:'From inside an organization, drift and evolution feel exactly the same. The difference is fidelity.', image:'assets/images/at-crossroads.png', href:'assets/perspectives/the-market-is-terrain-not-author.pdf', action:'Read the paper' },
  { id:'nike', featured:false, kind:'Strategy + Film Treatment', title:'Choose the Work', dek:'A case for returning Nike to the analog truth of effort, craft and the athlete.', image:'assets/images/evidence-access-impact.png', href:'assets/perspectives/choose-the-work.pdf', action:'View the treatment' },
  { id:'sentence', featured:false, kind:'Essay', title:'In Defense of a Sentence', dek:'On corporations, prophecy, and the cost of believing your own forecast.', href:'assets/perspectives/in-defense-of-a-sentence.pdf', action:'Read the essay' },
  { id:'unicorn', featured:false, kind:'Book', title:'Somebody’s Unicorn', dek:'A field guide for people whose range keeps breaking the containers they are handed.', href:'https://www.amazon.com/Somebodys-Unicorn-Gregory-Pohl/dp/B0H3877HZP/ref=sr_1_1?crid=32YGGLX171WFZ&dib=eyJ2IjoiMSJ9.LKBgQ3dtwk6WGCJKtDXHG-LPcFSY3lgK8mjts9USjSNwWFIie4qI-BFYlv_6vgtxiTMGxFMHZOG_zA4wzBTGgCp3rhoANKKR-6KhfGZgcPDi03uxYl7rvn0U_eOpRkuJELBnxAnN9R32pNqLdRTHHw.a97iMQMOvC5pUl_bAzAJNNRVGTalj-nK7JDFxJ6WAXc&dib_tag=se&keywords=somebody%27s+unicorn&qid=1786363785&sprefix=somebody%27s+un%2Caps%2C366&sr=8-1', action:'Buy the book' }
];
