window.WORK_ITEMS = [
  { id:'facts', featured:true, kind:'Field Note 001', title:'What If Your Facts Are Wrong?', dek:'Certainty isn’t evidence of truth. Usually it’s just a measure of how long a fact has gone unquestioned.', image:'assets/images/daily-observer.png', href:'assets/perspectives/what-if-your-facts-are-wrong.pdf', action:'Read the field note' },
  { id:'decay', featured:true, kind:'Organizational Diagnosis', title:'Positional Decay', dek:'How organizations hollow themselves out before a competitor ever beats them.', image:'assets/images/next-decade-rlt.png', href:'assets/perspectives/positional-decay.pdf', action:'Open the file' },
  { id:'coordination', featured:true, kind:'White Paper', title:'The Coordination Problem', dek:'Complexity is often only a polite word for unresolved structure. That’s where performance dies.', image:'assets/images/leadership-complexity.png', href:'assets/perspectives/the-coordination-problem.pdf', action:'Read the paper' },
  { id:'myhouse', featured:true, kind:'Original Concept', title:'My House', dek:'A global ranking system for football talent — built before the infrastructure exists. The upload is the competition. Rank is the product.', visual:'board', restricted:true, action:'View the concept' },
  { id:'rlt', featured:false, kind:'Radiopharmaceuticals', title:'The Second Wave Should Go Narrow', dek:'The next generation of RLT should prove more, in fewer patients, against a harder standard.', image:'assets/images/next-decade-rlt.png', href:'assets/perspectives/second-wave-should-go-narrow.pdf', action:'Read the perspective' },
  { id:'terrain', featured:false, kind:'Brand Strategy', title:'The Market Is Terrain, Not Author', dek:'From inside an organization, drift and evolution feel exactly the same. The difference is fidelity.', image:'assets/images/at-crossroads.png', href:'assets/perspectives/the-market-is-terrain-not-author.pdf', action:'Read the paper' },
  { id:'nike', featured:false, kind:'Strategy + Film Treatment', title:'Choose the Work', dek:'A case for returning Nike to the analog truth of effort, craft and the athlete.', image:'assets/images/evidence-access-impact.png', href:'assets/perspectives/choose-the-work.pdf', action:'View the treatment' },
  { id:'unicorn', featured:false, kind:'Book / Field Guide', title:'Somebody’s Unicorn', dek:'A field guide for people whose range keeps breaking the containers they are handed.', status:'In progress' }
];
